[package]
name = "locot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokei = "*"
plotters = "*"
git2 = "0.17.1"
tempfile = "3.5.0"
anyhow = "1.0.71"
csv = "1.2.2"
serde = "1.0.171"
